services:
  - type: web
    name: cadence-mychart-demo
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: |
      cd ../client
      npm ci
      npm run build
      cd ../server
      npm ci
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: TZ
        value: America/Los_Angeles